spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: c19941115
    platform: h2
    schema: classpath:db_inital/table.sql
    data: classpath:db_inital/data.sql